### ISSUE TITLE
option flow config_entry explicitly

### ISSUE THREAD

**Issue by patricschmitz** [LaggAt/hacs-govee#213]
Hi,

my govee integration stopped working, from the protocol logs:

Detected that custom integration 'govee' sets option flow config_entry explicitly, which is deprecated at custom_components/govee/config_flow.py, line 106: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/LaggAt/hacs-govee/issues

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?

Hope the information is sufficient.

Thanks,

pat
