### ISSUE TITLE
Getting "object has no attribute 'rate_limit_delay'" since updating to 2024.2.2. (I have the H6052 and H6141)

### ISSUE THREAD

**Issue by derek3rosen** [LaggAt/hacs-govee#157]
## Version of the custom_component
2023.11.1

## Configuration
Default config with my API key and 10 Poll Interval

## Describe the bug
I stated getting "object has no attribute 'rate_limit_delay'" since updating to 2024.2.2. 
I have the H6052 and H6141
There were no changes other than update. I think I was on 11.4 OS. Hard to tell if it was failing on 2024.2.1 - Did not look

Core:		2024.2.2
Supervisor	2024.01.1
OS			11.5

## Debug log

2024-02-20 10:36:16.699 WARNING (MainThread) [custom_components.govee] API is back online.
2024-02-20 10:36:16.699 WARNING (MainThread) [govee_api_laggat.api] Rate limit exceeded, check if other devices also utilize the govee API
2024-02-20 10:36:16.699 WARNING (MainThread) [custom_components.govee] Could not connect to Govee API: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2024-02-20 10:36:16.699 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?

**Comment by fender4645** [comment]
I don't think this is new with 2024.2.2. I've been on 2024.2.4 for over a week and it just started happening to me in the last 12 hours without any update. Looks like something on Govee's end maybe?

**Comment by derek3rosen** [comment]
For me, it was working fine until I updated it. Obviously the timing could be just a coincidence. I deleted the integration for now.

**Comment by fender4645** [comment]
I looked back through previous issues and the consensus was to re-download the HACS integration. I just deleted it and re-installed and when I went to configure (giving the config flow my API key), I get a slightly different error:

```
Cannot connect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 66, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/config_flow.py", line 32, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
```
I figured it must be something with Govee and I just needed to be patient. I then tried hitting the Govee API directly to see if the returned header would tell me when the API resets, and it came back perfectly fine with all of my device info. I ran:

```
G_URL = 'https://openapi.api.govee.com/router/api/v1/user/devices'
Headers = {
    'Content-Type': 'application/json',
    'Govee-API-Key': 'XXXXXXXXXXXXXXXXXX'
}

r = requests.get(G_URL, headers=Headers)
```
and it returned 200 with all of my device info. So now I'm not sure what the issue is. Assuming it resets within 24 hours, I'll try again tomorrow.

**Comment by fender4645** [comment]
FWIW, it's now working for me. I re-configured to poll every 60 seconds (instead of the default 10) per other threads related to rate limiting.

**Comment by LanceMcCarthy** [comment]
It would be very cool if the integration could check the HTTP response header for the presence of the  `X-RateLimit-Reset` header. This would prevent some headache :)
