### ISSUE TITLE
Govee HACS integration HA not working (SOLVED)

### ISSUE THREAD

**Issue by catalans1980** [LaggAt/hacs-govee#251]
It's been a while. Been working great, but one day it just stopped working. I have the same API key, i don't know what to do in order to make it work.

"It hasn't been able to be configured" (No se ha podido configurar) appears on the integration site of HA.

Some logs:

2025-07-16 09:56:50.639 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'govee' sets option flow config_entry explicitly, which is deprecated at custom_components/govee/config_flow.py, line 106: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/LaggAt/hacs-govee/issues
2025-07-16 09:58:25.315 WARNING (MainThread) [custom_components.govee] API is back online.
2025-07-16 09:58:25.324 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 73, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-07-16 10:00:06.247 WARNING (MainThread) [custom_components.govee] API is back online.
2025-07-16 10:00:06.255 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 73, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-07-16 10:00:55.662 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2025-07-16 10:00:55.662 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/govee_api_laggat/govee_api_laggat.py", line 300, in _schedule_get_devices
    await asyncio.sleep(SCHEDULE_GET_DEVICES_SECONDS)  # TODO: define SCHEDULE_GET_DEVICES_SECONDS
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SCHEDULE_GET_DEVICES_SECONDS' is not defined
2025-07-16 10:01:03.537 WARNING (MainThread) [custom_components.govee] API is back online.
2025-07-16 10:01:03.544 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 73, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-07-16 10:01:32.786 WARNING (MainThread) [custom_components.govee] API is back online.
2025-07-16 10:01:32.793 INFO (MainThread) [custom_components.govee.learning_storage] Loaded learning information from /config/govee_learning.yaml.
2025-07-16 10:01:32.794 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 73, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-07-16 10:02:01.962 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/govee_api_laggat/govee_api_laggat.py", line 300, in _schedule_get_devices
    await asyncio.sleep(SCHEDULE_GET_DEVICES_SECONDS)  # TODO: define SCHEDULE_GET_DEVICES_SECONDS

**Comment by Nyrup** [comment]
I have the same issue.... Must have stopped after updating the HA Core at some point.

EDIT: Oh well, there is already a PR for this issue: https://github.com/LaggAt/hacs-govee/pull/250/commits/22ad46be54dc5318006dca10283098d80576722e

And it works great 👍

**Comment by LLin233** [comment]
> I have the same issue.... Must have stopped after updating the HA Core at some point.
> 
> EDIT: Oh well, there is already a PR for this issue: [22ad46b](https://github.com/LaggAt/hacs-govee/commit/22ad46be54dc5318006dca10283098d80576722e)
> 
> And it works great 👍

wow that change was 2 days ago, I guess we need to wait for a new release to carry that change

**Comment by LLin233** [comment]
Also you may check #236 
There's a solution change

**Comment by catalans1980** [comment]
Solved here https://github.com/LaggAt/hacs-govee/issues/236#issuecomment-3082811151!

Thanks @LLin233
