### ISSUE TITLE
Integration not working, configuring error: object has no attribute 'rate_limit_delay'

### ISSUE THREAD

**Issue by KitHubek** [LaggAt/hacs-govee#172]
Configuration stopped working at all. Have 2 devices (H605C and H6067) and all not working. Configuration error. Devices working ok via Govee app.

Version of the custom_component
2023.11.1

Logs:

```
Rejestrator: custom_components.govee
Źródło: custom_components/govee/__init__.py:66
integracja: Govee (dokumentacja, Problemy)
Pierwsze zdarzenie: 21:54:59 (5 zdarzenia)
Ostatnio zalogowany: 22:45:58

Could not connect to Govee API: API: API-Error 500: {"message":"service is busy please try again later","status":500}
```

AND

```
Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:604
Pierwsze zdarzenie: 21:54:59 (5 zdarzenia)
Ostatnio zalogowany: 22:45:58

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?
```

**Comment by masanjose21** [comment]
Having the same issue just now but also noticed an earlier warning in the logs:

```
Logger: custom_components.govee
Source: custom_components/govee/__init__.py:72
integration: Govee ([documentation](https://github.com/LaggAt/hacs-govee/blob/master/README.md), [issues](https://github.com/LaggAt/hacs-govee/issues))
First occurred: 5:45:30 PM (1 occurrences)
Last logged: 5:45:30 PM

Could not connect to Govee API: API: API-Error 500: {"message":"service is busy please try again later","status":500}
```

Could it be service related?

**Comment by remipregh** [comment]
Same issue for me. After a bit of digging and looking at the Govee API doc, I think it's an issue with the API service rather than the integration. Let's hope it gets resolved tomorrow!

**Comment by nerotrobe** [comment]
I'm seeing the above issue as well, the intergration isn't working. But I'm also seeing this message in my logs:

2024-09-16 18:44:56.456 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f8dee1550>, '/usr/local/lib/python3.12/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'govee' at custom_components/govee/__init__.py, line 53: hub = await Govee.create( (offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/LaggAt/hacs-govee/issues

**Comment by hfbauman** [comment]
I'm also seeing this issue. I tried deleting and re-adding the integration and I get the message that `Cannot connect. Is the API-Key correct and the internet connection working?`

**Comment by mukul-k** [comment]
Same issues for me after updating to 2024.9.2

**Comment by frankandsoo** [comment]
Same issue for me after a restart earlier today.

**Comment by talormanda** [comment]
Same / broken for me and govee2mqtt too.

**Comment by thomast1906** [comment]
Yeah same here :(

**Comment by INVADIA666** [comment]
Same for me after updating to 9.2 , it was working perfectly fine before .

**Comment by eyesonly09** [comment]
This is happening to me on 9.1, it might not be related to the HA version but to Govee's service.

**Comment by ramorimdias** [comment]
Same issue here, stopped working tonight on it's own, didn't update anything on HA. Must be Govee related.

**Comment by ml0renz0** [comment]
Same here, changed nothing on my HA config. I also think it has to be something related to changes on Govee API service

**Comment by inertia666** [comment]
Yes same here. I emailed govee asking if my API key had expired. No reply yet so i am sure it will get sorted.

**Comment by inertia666** [comment]
> Glad to see it's not just me. I always assume something wrong at my end and have to stop myself diving right in, reinstalling integrations etc.
> 
> AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?
> 
> Was working up until about 12 hours ago!

tell me about it...spent like an hour trying to sort it-

**Comment by inertia666** [comment]
It's actually really annoying a tv backlight requires an internet connection to work or bluetooth when most other Govee lights have a LAN api.

**Comment by cepheid-variable** [comment]
> It's actually really annoying a tv backlight requires an internet connection to work or bluetooth when most other Govee lights have a LAN api.

Mistakes were made when I picked these lights...  Lesson learned :)

**Comment by beanboyrjs** [comment]
govee2mqtt seems to work beautifully! I might be switching to that Add-On now.

**Comment by ItsMeNJC** [comment]
I’m having the same issue with my Govee devices. 
![IMG_0048](https://github.com/user-attachments/assets/c1e686a4-3567-4a75-9b06-9ecd1b068059)

**Comment by ml0renz0** [comment]
> govee2mqtt seems to work beautifully! I might be switching to that Add-On now.

I did, and now the devices that can be controlled through Local API (LAN) do not have that annoying 2 seconds delay.

This issue made me re-evaluate `gove2mqtt` and, for me, local API is better than anything else.

**Comment by cepheid-variable** [comment]
While I'm here and keeping an eye on this thread, I have a 5m led strip running up the skirting on my stairs.  I control it via home assistant and an aqara zigbee motion sensor, currently using the dreaded govee api.  Can anyone recommend a replacement strip that uses the local api?  thanks!

**Comment by ml0renz0** [comment]
> While I'm here and keeping an eye on this thread, I have a 5m led strip running up the skirting on my stairs.  I control it via home assistant and an aqara zigbee motion sensor, currently using the dreaded govee api.  Can anyone recommend a replacement strip that uses the local api?  thanks!

[These Govee devices](https://app-h5.govee.com/user-manual/wlan-guide) have Local API (needs to be enabled first in govee configuration) and can be used with `govee2mqtt` integration.

**Comment by ItsMeNJC** [comment]
> While I'm here and keeping an eye on this thread, I have a 5m led strip running up the skirting on my stairs. I control it via home assistant and an aqara zigbee motion sensor, currently using the dreaded govee api. Can anyone recommend a replacement strip that uses the local api? thanks!

If you’re buying new, buy one of their Matter enabled strips. I have the Neon Rope Light (H61A2) that supports local api. They have recently released the second gen of this, so I assume it will also have local api.

**Comment by KitHubek** [comment]
i just migrated to https://github.com/wez/govee2mqtt and all working ok. Last release of this govee inytergration was Nov 19, 2023. looking at the reported problems here to anyone I suggest switching to the mentioned repo to keep the devices running in HA.

**Comment by wwelles** [comment]
Same problem, also having success with govee2mqtt that I already had it setup before.

**Comment by chadpatt** [comment]
I have a lot of experience with python. I almost 100% guarantee that the issue is an underly module in either home core or a pip package that has been updated.  I took their API examples and it works perfectly using them to call the external API using the API-Key. So, not key and not Govee API.  Not really sure how to get into the home core for debugging, but will keep looking.

**Comment by Biggiz** [comment]
Same here. I‘ll try this local api thing tomorrow

**Comment by WinesProof** [comment]
@chadpatt , were you using the v2.0 API or the v1.0 one? I tried a python request to get devices using the v1.0 one (https://openapi.api.govee.com), and it succeeded, but the v2.0 one (https://developer-api.govee.com) returned ```{"message":"service` is busy please try again later","status":500}```

**Comment by kmercer6** [comment]
Sadly only 1 of my 5 Govee products support local API.  https://www.home-assistant.io/integrations/govee_light_local/

**Comment by chadpatt** [comment]
@WinesProof , Here is what I tested with to get details.  And then toggled on/off light with the second curl command.

Get
curl -X GET "https://openapi.api.govee.com/router/api/v1/user/devices" -H "Content-Type: application/json" -H "Govee-API-Key: xxxxx"

Post
curl -X POST "https://openapi.api.govee.com/router/api/v1/device/control" \
-H "Content-Type: application/json" \
-H "Govee-API-Key: xxxxxxx" \
-d '{
  "requestId": "uuid",
  "payload": {
    "sku": "H6054",
    "device": "E7:D2:A4:xx:xx:xx:xx",
    "capability": {
      "type": "devices.capabilities.on_off",
      "instance": "powerSwitch",
      "value": 0
    }
  }
}'

**Comment by WinesProof** [comment]
That's the v1 API. Try the v2 one, and you'll see the 500 error we're all
getting

**Comment by jeromelmd** [comment]
> Same here, changed nothing on my HA config. I also think it has to be something related to changes on Govee API service.
> 
> I tried removing and reinstalling the integration but it fails:
> 
> ![Screenshot_20240917-095656.png](https://private-user-images.githubusercontent.com/11718206/368066450-203722b8-7e48-4375-b8b0-d9352e6fff57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTUyMTgsIm5iZiI6MTcyNjYxNDkxOCwicGF0aCI6Ii8xMTcxODIwNi8zNjgwNjY0NTAtMjAzNzIyYjgtN2U0OC00Mzc1LWI4YjAtZDkzNTJlNmZmZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDIzMTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDY1MTJmZjdkZTljMzcxMDc4M2QxNTc2NjcwNGFiNTU0OGM1NGNlODVjOTRmNzQzNGZkMjkxYmIzODdlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HBy9DPtlvyHDmd9DviGPjmbZQ91NWs3fYlhPBHa4gyo)

Having this same issue

**Comment by accordxtc** [comment]
Add me to the list of poor souls with non Lan Control devices to this list. It's not Govee even sells a bulb that does Lan Control to upgrade to

**Comment by innovatorgit** [comment]
+1

**Comment by irislich** [comment]
Same here, I spent a few hours troubleshooting before coming here.

**Comment by mafmafmafmaf** [comment]
Fwiw, it's just self-corrected for me. I also had the same errors after updating to 9.2 (could be coincidence), went 2 days with the api error, and now it came back to normal, after just another reload of the integration.

**Comment by hfbauman** [comment]
@mafmafmafmaf thanks for saying something, I just checked and I was able to add it back. I wonder if everyone updating/restarting at the same time was enough to overwhelm the server.

**Comment by kmercer6** [comment]
Mine is also good once again after the reload.  Thanks for the update back in business

**Comment by challgren** [comment]
Just reloaded mine and it works now!

**Comment by inertia666** [comment]
> > govee2mqtt seems to work beautifully! I might be switching to that Add-On now.
> 
> I did, and now the devices that can be controlled through Local API (LAN) do not have that annoying 2 seconds delay.
> 
> This issue made me re-evaluate `gove2mqtt` and, for me, local API is better than anything else.

It also works with non local api devices. I have also moved to this project.

**Comment by inertia666** [comment]
> Fwiw, it's just self-corrected for me. After updating to 9.2 (could be coincidence), I went 2 days with the api error, and now it came back to normal, after just another reload of the integration.

I got a mail back from Govee apologising that their server was down.

**Comment by frosthal** [comment]
I have no updated anything and just reloading today the integration solved the problem.
Tonight this action didn't solved the problem.

**Comment by cepheid-variable** [comment]
Back to relying on external servers we go!  I'm looking at the Aqara T1 to replace my stairs lights and this is the kick up the backside I needed.  Cheers everyone.

**Comment by James62370** [comment]
Seems to be working again, I didn't make any changes so was probably something on their server end.

**Comment by wwelles** [comment]
Same here, working today.

**Comment by TobiTenno** [comment]
I'm seeing this pretty constantly with the same error as others. Can we make the change ourselves? This feels like the library changed and the integration didn't update?

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 08:52:58 (2 occurrences)
Last logged: 08:53:35

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?
```

**Comment by philharmonie** [comment]
> I'm seeing this pretty constantly with the same error as others. Can we make the change ourselves? This feels like the library changed and the integration didn't update?
> 
> ```
> Logger: homeassistant.config_entries
> Source: config_entries.py:594
> First occurred: 08:52:58 (2 occurrences)
> Last logged: 08:53:35
> 
> Error setting up entry govee for govee
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
>     await hub.rate_limit_delay()
>           ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?
> ```

Im getting the exact Same error
