### ISSUE TITLE
Not working with 2022.3.3

### ISSUE THREAD

**Issue by kbrohkahn** [LaggAt/hacs-govee#62]
## Version of the custom_component
Latest

## Configuration
Using configuration UI

## Describe the bug
Govee integration was not working and showing an error in the integrations page. Removed integration, but now it won't even add.

## Debug log

```
Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

```

**Comment by kbrohkahn** [comment]
Whoops, my AdBlocker started blocking developer-api.govee.com, disregard.
